### ISSUE TITLE
Update docs on search and sort view options like name, sort link etc

### ISSUE THREAD

**Issue by aditya7iyengar** [aditya7iyengar/rummage_phoenix#19]

**Comment by alxndr** [comment]
Can I use Rummage to add a search route/action to a [`mix phoenix.gen.json`-generated resource](https://hexdocs.pm/phoenix/Mix.Tasks.Phoenix.Gen.Json.html)? Does it already add a route which accepts parameters to build the search?

**Comment by aditya7iyengar** [comment]
How `Rummage.Phoenix` works right now is it just performs a get request from the form helper for the `index` action. So, no, it doesn't define routes. Although, since `Rummage.Ecto` and `Rummage.Phoenix` are separate entities, you can define a route for search which accepts parameters and makes a call to `rummage` in the action. You won't even need `Rummage.Phoenix` to accomplish this task. 😄
