### ISSUE TITLE
Default pagination not biting through controller

### ISSUE THREAD

**Issue by jekku** [aditya7iyengar/rummage_phoenix#23]
As suggested, I have already set my config vars into setting the default_per_page as I like

```exs
config :rummage_ecto, Rummage.Ecto
  default_repo: MyApp.Repo,
  default_per_page: 3
```

I confirmed that this configuration has been applied by checking IEx

```exs
Rummage.Ecto.Config.default_per_page() //returns 3
```

However when I make a rummage query:

```ex
def index(conn, params) do
  {query, rummage} = Something.rummage(Something, params['rummage'])
  #more code here
end
```

The value of rummage returned by the function is:

```ex
%{"paginate" => %{"max_page" => "1", "page" => "1", "per_page" => "10",
    "total_count" => "4"}, "search" => %{}, "sort" => %{}}
```

Whereas I already set the default_per_page as 3.

Any idea why this happens???

**Comment by aditya7iyengar** [comment]
Good catch! And thanks for pointing this out. The fix is in [this](https://github.com/aditya7iyengar/rummage_phoenix/pull/24) PR. I will add it in the next release (which will be next weekend, hopefully). In the meantime, would referencing the master branch should suffice. 😃

**Comment by jekku** [comment]
Thanks @aditya7iyengar
