### ISSUE TITLE
Make work with phoenix >1.3.0

### ISSUE THREAD

**Issue by mbenatti** [aditya7iyengar/rummage_phoenix#29]
```Elixir
# marcos @ marcos-ThinkPad-T440 in ~/xxx/apps/tools_feed_web on git:master x [10:22:27] C:1
$ mix deps.get
Running dependency resolution...

Failed to use "phoenix" (version 1.3.0-rc.1) because
  phoenix_live_reload (version 1.0.8) requires ~> 1.0 or ~> 1.2-rc
  rummage_phoenix (version 1.0.0) requires ~> 1.2.1
  mix.lock specifies 1.3.0-rc.1
```

**Comment by aditya7iyengar** [comment]
#28 This is work in progress. I hope to get it in soon

**Comment by mbenatti** [comment]
@aditya7iyengar Thank you!

I tried to make it work with phoenix 1.3 and rammage_ecto 1.1.0 but there's a work to do in both projetcs...

Some error's that I got and can be fixed with this change:

in file  lib/rummage_phoenix/hooks/views/paginate_view.ex
```Elixir
-    per_page = String.to_integer(paginate_params["per_page"]) || Rummage.Phoenix.default_per_page
+    per_page = if !is_nil(paginate_params["per_page"]), do: String.to_integer(paginate_params["per_page"]), else: Rummage.Phoenix.default_per_page
```
- Here paginate_params["per_page"]) can be null and per_page configuration is an Integer not an String

--

I don't understand how rummage handles a request. using params in url I got and error
Using params like `rummage[sort][field]=name.asc&rummage[paginate][page]=1&rummage[paginate][per_page]=3` this 
I got in `params[rummage]` :
`%{"paginate" => %{"page" => 1, "per_page" => 3}, "sort" => %{"field" => "name.asc"}}`

But changing to this run without error(but the features aren't working properly)
`%{"rummage" => %{"paginate" => %{"page" => 1, "per_page" => 3}, "sort" => %{"field" => "name.asc"}}}`

note: This module is amazing and can be a reference in hex for sorting, page and search...

**Comment by agustif** [comment]
Hi @aditya7iyengar I wonder if 1.3 is the reason you stopped your plans on medium.

Im planning on using rummage-phoenix for a pretty simple client database, and with all the 1.3 mystery seems everyone is on a halt.

Let us know your plans, anyways Im guessing if I have a hurry, I should build it in 1.2 and update when there's a clear path for it.

**Comment by aditya7iyengar** [comment]
@mbenatti Thanks for the suggestion! I have a PR open in `rummage_ecto` for this purpose. I was down with a fever last week so couldn't get much done, but this should be all set as soon as I can find 5 hours to work on this. I will update you guys.

@agustif 1.3 is one of the reasons why my plans are on a halt. Hopefully, I can roll this out asap. In the meantime feel free to let me know if you guys have any suggestions.

**Comment by agustif** [comment]
It's not a suggestion, but I do wonder if rummage and ecto could get along on the same UI, what I mean is, prefer a thousand times the rummage UI/UX which is simple but powerful, exAdmin ads a lot of fields for filtering/search which are not really needed for me in the ux part (I mean, it looks more like PHPMyAdmin, than a custom interface)

BUT. I really like exAdmin for the dashboard/actions/and how it structures diferent models in tabs and such, So I'm guessing I want to use only exAdmin for the layout logic, and rummage for the view/template logic of each model.

I don't know, haven't really tried yet, let me know if you think is achievable and I might try on a PR

**Comment by aditya7iyengar** [comment]
@agustif Sounds like a `rummage_ex_admin` hex package to me. I'm not sure about including it in either `rummage_ecto` or `rummage_phoenix`, but if I see people wanting to use it, it could be an a module that acts as an adapter for `rummage`. I have been flirting with the idea of writing adapters for `rummage_ecto` and `rummage_phoenix` being one of them. It could lead to us having more adapters with other hex packages. But it's quite farfetched at this point. 😄

**Comment by aditya7iyengar** [comment]
This can now be used with phoenix 1.3 by calling `override: true`.
