### ISSUE TITLE
Limit pagination links to X number of items at once

### ISSUE THREAD

**Issue by aaronpearce** [aditya7iyengar/rummage_phoenix#30]
Would it be possible if not already existing to be able to limit `pagination_link(@conn, @rummage)` to only show X number of pages at a time with links at either end of the links to quickly jump to the start or end?

Below is an example of what happens if you have a lot of data currently.
<img width="1178" alt="screen shot 2017-05-02 at 12 29 52 pm" src="https://cloud.githubusercontent.com/assets/422836/25599801/3b8d2936-2f33-11e7-8984-5d90477f3768.png">

**Comment by aditya7iyengar** [comment]
@aaronpearce This is a work in progress in this PR: #28. It's taking me a little longer to get this done as I want it to work with both phoenix 1.2 and 1.3

**Comment by mazli84** [comment]
@aditya7iyengar That's cool. Any work around meanwhile?

**Comment by aditya7iyengar** [comment]
@mazli84 Unfortunately not. You could write a small helper for pagination links. :smile:
