### ISSUE TITLE
Shortening very long pagination bars

### ISSUE THREAD

**Issue by asconix** [aditya7iyengar/rummage_phoenix#32]
Hi, I checked the code but maybe overlooked it. I have a big amount of data I paginate, in this case it's 600 pages with 25 entries each. The pagination bar renders "Previous 1 2 3 4 5 6 7 8 9 10 11 etc etc 600 Last", which of course in case of 600 pages is sort of ugly. Is there a way to render "Previous 1 2 3 ... 598 599 600 Last" ? So basically it's about how to shorten the pagination bar.

Cheerio,
Christoph

**Comment by aditya7iyengar** [comment]
Hi @asconix! Thanks for pointing out this issue. Currently we have the same problem reported in #30 and I'm working on fixing this with the new update.
