### ISSUE TITLE
question: Does this perform "incremental search" AKA "search as you type"?

### ISSUE THREAD

**Issue by dede5** [aditya7iyengar/rummage_phoenix#33]
I tried looking through the docs and animated gifs but I couldn't tell. Thanks for building this great framework.

**Comment by aditya7iyengar** [comment]
@dede5 `Rummage.Phoenix` currently doesn't support this feature. I think this could be accomplished using channels or even simple javascript. My intention with `Rummage.Phoenix` was to support basic templates/views with `Rummage.Ecto` and lay a pattern for people to follow. 

I hope this answers your question! :smile:
