### ISSUE TITLE
trouble with nested resource url helpers

### ISSUE THREAD

**Issue by sunchess** [aditya7iyengar/rummage_phoenix#34]
Hi!
Can the mix support nested resouce links like `group_post_path(@conn, :index, group.id)`?

In routes.ex it looks like 
   

```
  resources "/groups", GroupController do
       resources "/posts", PostController
  end

```
 Thanks!

**Comment by aditya7iyengar** [comment]
This won't be straightforward with `Rummage.Phoenix`. I recommend using `Rummage.Ecto` with a custom view for this kind of route. :smile:
