### ISSUE TITLE
pagination problem: url always is module's path for :index

### ISSUE THREAD

**Issue by toreal** [aditya7iyengar/rummage_phoenix#38]
Hi 
Thank you for the great module. 
I face a problem. The url of the pagination always return about the module's path.
Can it return the current url?
for example:
MyApp.Router.Helpers.url(conn) <> conn.request_path which would return a result like "http://localhost:4000/categories/4/products".

When I do category that will be very helpful. This url will get the products that belong to the category. The view shares with the product view. Thus, the template will render the products.

https://github.com/vinsol/nectarcommerce/blob/master/apps/nectar/web/templates/category/products.html.eex

I try to change the linker in paginate_view.ex as following.

 `   querystr= Plug.Conn.Query.encode(%{rummage: Map.put(rummage, "paginate", %{"per_page"=> per_page, "page"=> x})})`
`    raw_link(x, conn.request_path <> "?" <> querystr )`

**Comment by aditya7iyengar** [comment]
That's a great catch, @toreal! I think we can make the `index_path` default to `struct_path`, but also let people pass in a parameter to the `pagination_link` function. 
Thanks for pointing this out!

**Comment by jeroenbourgois** [comment]
@aditya7iyengar do you have an example somewhere on how to pass it as a param? I cannot figure it out :) it is still using the :index path.
