### ISSUE TITLE
Getting errror on pagination when model doesn't match controller

### ISSUE THREAD

**Issue by grounded-warrior** [aditya7iyengar/rummage_phoenix#40]
``` 
** (UndefinedFunctionError) function MyApp.Router.Helpers.adminvideo_path/3 is undefined or private. Did you mean one of:

      * admin_path/2
      * admin_path/3
      * admin_video_path/2
      * admin_video_path/3
      * admin_video_path/4
```

My controller is `MyApp.AdminVideoController` and my model is `MyApp.Video`

**Comment by grounded-warrior** [comment]
Seems to be this line `String.to_atom("#{opts[:struct]}_path")`

**Comment by conn** [comment]
:wave:

**Comment by grounded-warrior** [comment]
Any work arounds for this??

**Comment by conn** [comment]
Have you tried using `admin_video_path` instead of `adminvideo_path`?

**Comment by ericsullivan** [comment]
This commit should take care of it: https://github.com/aditya7iyengar/rummage_phoenix/commit/b0b023137d568c81b9dd2c7fa5be6e143801ca90
