### ISSUE TITLE
function nil.all/1 is undefined or private

### ISSUE THREAD

**Issue by Merff** [aditya7iyengar/rummage_phoenix#46]
Hi, I try to use with Phoenix 1.3, Elixir 1.5.2
get `(UndefinedFunctionError) function nil.all/1 is undefined or private
    nil.all(#Ecto.Query<from p in subquery(from p in BpPro.Accounts.Profile), select: count(p.id)>)`
when call `Rummage.Ecto.rummage(Profile, params["rummage"])`

I did as shown in https://github.com/aditya7iyengar/rummage_phoenix/issues/39
Any idea?

**Comment by aditya7iyengar** [comment]
Hi @Merff, Looks like there hasn't been a `repo` set up in the configurations. Do you want to give this a  try and let me know?
```elixir
Rummage.Ecto.rummage(Profile, params["rummage"], repo: BpPro.Repo) # or whatever your repo name is
```

You could also set a repo in `rummage_ecto` configuration in your `ecto` app:
in `config.exs`
```elixir
config :rummage_ecto, Rummage.Ecto
  # other configuration keys
  default_repo: BpPro.Repo
```

**Comment by Merff** [comment]
It works, tnx a lot!
